# Generated by Django 2.1.4 on 2019-01-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departemento',
            new_name='Departamento',
        ),
    ]
